### ISSUE TITLE
A README

### ISSUE THREAD

**Issue by gleachkr** [Carnap/Carnap-Contrib#2]
I mean, c'mon.

**Comment by rzach** [comment]
LOL maybe this will answer a question I'll hgave name whether these css/js will automatically show up on carnap.io or do you still have to upload them?

**Comment by gleachkr** [comment]
Nope! You can link directly to the files on github, using something like [jsdelivr](https://www.jsdelivr.com/?docs=gh). But the README should definitely include official and up to date links of this kind.
